modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/DragonsPlusMinecraft/VisualityReforged/issues/"
[[mods]]
modId="visuality"
version="${version}"
displayName="Visuality: Reforged"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/visuality-forge"
logoFile="pack.png"
credits="Thanks PinkGoosik for the original work!"
authors="LimonBlaze"
description="Little visual improvements by adding a bunch of new particles."
[[dependencies.visuality]]
modId="neoforge"
type="required"
versionRange = "[21.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.visuality]]
modId="minecraft"
type="required"
versionRange = "[1.21,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="visuality.mixins.json"