@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.github.channelingmc.visuality.config;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;