@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.github.channelingmc.visuality.particle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;