@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package plus.dragons.visuality.particle;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;