name: publish-modrinth

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Brachyura directory
        uses: actions/cache@v2
        with:
          path: |
            .brachyura
            ~/.brachyura
          key: ${{ runner.os }}-brachyura-${{ hashFiles('**/Buildscript.java') }}
          restore-keys: ${{ runner.os }}-brachyura

      - name: Build with Brachyura
        run: java -jar brachyura-bootstrap-0.jar build

      - name: Publish artifacts to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: rI0hvYcd
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: build/libs/!(*-@(dev|sources)).jar

          version-type: beta
          loaders: |
            fabric
            quilt
            
          game-version-filter: releases

          dependencies: |
            fabric-api(required){modrinth:P7dR8mSH}{curseforge:306612}#(ignore:github)
            cloth-config(required){modrinth:9s6osm5g}{curseforge:348521}#(ignore:github)

          java: |
            17

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
