name: publish-curseforge

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build artifacts
        run: ./gradlew build
      - name: publish artifacts
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          curseforge-id: 704256
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files-primary: build/libs/!(*-@(dev|sources)).jar
          files-secondary: build/libs/*-@(dev|sources).jar

          version-type: beta
          loaders: |
            forge
          game-versions: |
            1.19
            1.19.1
            1.19.2
            1.19.3

          java: |
            17

          retry-attempts: 2
          retry-delay: 10000
